### ISSUE TITLE
feature request: key-value support

### ISSUE THREAD

**Issue by shawnl** [pts/pts-line-bisect#2]
I have a file with sorted keys, but values are attached

key:value
gccgo:gccgo
gccgo-5:gccgo-5

et cetera

I need to give it a seperator token and then retrieve the values.

**Comment by pts** [comment]
This sounds like a useful feature.

Please note that your input file is not sorted, and thus binary search won't work on it. Here is the sorted version:

```
gccgo-5:gccgo-5
gccgo:gccgo
```

You can use the the `-p` flag for prefix search, and use *cut(1)* or *awk(1)* on Unix to remove the key:

```
$ ./pts_lbsearch -p kv.txt gccgo-5: | awk '{gsub(/^.*:/, "", $0); print}'
gccgo-5
```

If you want `-p` implemented in the Python version, and you don't know how, then please file a separate issue for that.

I'm not going to implement this feature, because I don't want to substantially increase the complexity of the code (either C or Python), because that code is also educational (http://pts.github.io/pts-line-bisect/line_bisect_evolution.html).

pts-line-bisect is free software (GPL v2), so you can (fork and) reuse the code and write your own tool with the desired key-value lookup features. If you happen to do so, please let me know!

**Comment by shawnl** [comment]
The work around is to separate the key and value with a NUL '\0'. That way it is sorted if sorted by keys.

**Comment by shawnl** [comment]
works, with no modifications! https://github.com/shawnl/command-not-found

The last thing would be to turn it into a library to avoid the exec() costs.

**Comment by pts** [comment]
Great job! You can avoid the exec() by

```
extern int lbsearch_main(int argc, char **argv);

int main(int argc, char **argv) {
  ...
  lbsearch_main(...);
  ...
  return 0;
}

#define main lbsearch_main
#include "pts_lbsearch.c"
```

You may have to make some small changes to pts_lbsearch.c. Feel free to do so!

**Comment by shawnl** [comment]
I'm trying to re-write it with mmap(), which should be easy, but those corner cases are tricky.

https://github.com/shawnl/pts-line-bisect/blob/master/bisect.c

the database I am working with is attached as "db" in the repo, which works with your version.

You don't have to help me, there is no warranty.

**Comment by shawnl** [comment]
I got it working!
